### ISSUE TITLE
Add option to deploy as a single binary rather than in a container

### ISSUE THREAD

**Issue by tomdee** [projectcalico/libnetwork-plugin#10]
We could use PyInstaller (like we do for calicoctl) but see https://github.com/benoitc/gunicorn/issues/669

**Comment by matthewdupre** [comment]
Duplicate of https://github.com/projectcalico/calico-containers/issues/1003

**Comment by tomdee** [comment]
Doesn't look like a dupe to me, can you elaborate?

**Comment by tomdee** [comment]
This is now just documentation so closing. If someone wants it we can raise a docs issue
