### ISSUE TITLE
Use Docker container labels to populate the workloadEndpoint

### ISSUE THREAD

**Issue by rtoma** [projectcalico/libnetwork-plugin#102]
v1.0.0-rc2 creates a workloadEndpoint resource without labels. To use the full power of policy selectors in policies we'd like to enrich the workloadEndpoints with labels passed via the `docker run ... --label foo=bar <image>` construct.

I've done some prototyping already.

What does not work:
- Inside a CreateEndpoint method call its impossible to get the container's label, because the NetworkInspect response does not include the container's ID yet.
- Same goes for the Join method.
- The container ID is available in the NetworkInfo method call, but a ContainerInspect on the container ID blocks forever. My assumption: Docker locks on the container object before doing the NetworkInfo call.

What does work (I've got a working prototype):
- Start a goroutine once the workloadEndpoint has been created in CreateEndpoint
- Inside the goroutine: start polling NetworkInspect until its updated with the container ID
- Then attempt a ContainerInspect on the ID to get the labels.
- Upon success: filter the labels for the ones starting with "org.projectcalico.\<something\>." and add those (without prefix) to the workloadEndpoint and do an update.
- If NetworkInspect or ContainerInspect fails, try again, until success.

I've created this issue to start a spec discussion, so we all feel comfortable with this solution.

Note: once https://github.com/docker/docker/pull/27638 gets merged and released it may give us a cleaner method of populating a workloadEndpoint, but I can not wait.

/cc @lxpollitt @tomdee

**Comment by matthewdupre** [comment]
Would be great to have this in.  It's sad that we have to do the polling, but I'm OK with it given Docker doesn't support this properly.

One possible suggestion: should we add a label that indicates that we haven't found the real labels yet?  This might be helpful to people.

**Comment by robbrockbank** [comment]
Given that this may be a temporary solution, I feel that we should have explicit buy-in either through an environment variable or a network option.  The problem with the latter is that it would require storing and querying additional network data, so I'd personally plump for an environment.

Perhaps introduce two environments to (1) turn off profile creation   (2) turn on container labels,  or a single "mode" environment (profile, container label, netopt label).  Whilst I'd prefer a single "mode", I think that would make migration to a new mode difficult.

WDPT?

**Comment by rtoma** [comment]
What about this:
- don't create profiles if env key CALICO_DONT_CREATE_PROFILES is set
- don't label the WEP if env key CALICO_DONT_LABEL_WEP is set

If CALICO_DONT_LABEL_WEP is unset, two methods of label discovery are executed in order, where set labels cant be overwritten by later methods. First 'container label' followed by 'netopt'. I suggest this order because 'netopt' is not available yet and it depends on a specific Docker version, where 'container label' works on Docker since uhmm 1.6? And order can be changed in the future.

**Comment by tomdee** [comment]
Thanks @rtoma (and @robbrockbank ) this sounds good to me.

**Comment by rtoma** [comment]
Hi @tomdee I've added the switch support with https://github.com/projectcalico/libnetwork-plugin/pull/103/commits/97bf63ac773267b059b23176eddf9d8d36c663ed

**Comment by caseydavenport** [comment]
This was fixed in https://github.com/projectcalico/libnetwork-plugin/pull/103
