### ISSUE TITLE
Workload name 'libnetwork' is unhelpful

### ISSUE THREAD

**Issue by matthewdupre** [projectcalico/libnetwork-plugin#105]
We need to expose a better workload name - the container name or id would be best.  The EndpointID being the only identifying field is painful.

**Comment by rtoma** [comment]
Info on the container is not available during the CreateEndpoint call, as Docker will add the container to the NetworkInspect container list after the Join call has returned.

Can you change a workload name after its creation? Or is it consider part of the key?

With https://github.com/projectcalico/libnetwork-plugin/pull/103 the workload can be enriched with anything from a ContainerInspect. Maybe add code there to add a "containerId" / "containerName" label?

**Comment by matthewdupre** [comment]
Ahh, good point @rtoma - it is indeed part of the key, so the only way I can see to fix this is to delay the work from CreateEndpoint entirely, or workaround it such as you suggest.
