### ISSUE TITLE
rc3 goes dead with Too many open files

### ISSUE THREAD

**Issue by rtoma** [projectcalico/libnetwork-plugin#107]
My reproduction with rc3 (68ca090):
- restart libnetwork-plugin
- have a Calico network created
- exec `while :; do docker run --rm --net calico busybox date;done` - thus triggering calls to the plugin
- run a watch on `lsof -p $(pgrep -f libnetwork-plugin) | grep -c socket` and see the number going up
- keep running the container create loop and eventually (in our case once the counter is 1014) spot this in the libnetwork output/log:
```
level=error msg="Veth creation error, hostInterfaceName=caliba064851e4e, tempInterfaceName=tempba064851e4e: too many open files"
```
- after this event the plugin logs these events and returns HTTP 500 to Docker:
```
level=error msg="Hostname fetching error: open /proc/sys/kernel/hostname: too many open files"
```
- and it never recovers, only a restart helps and the leak starts all over

My assumption: the `dockerCli` created in https://github.com/projectcalico/libnetwork-plugin/blob/master/driver/network_driver.go#L141 is not closed anywhere. I will try a defer close.

**Comment by lwr20** [comment]
This is a great bug to find - thank you very much @rtoma
