### ISSUE TITLE
Populate workloadendpoint with labels from plugin configuration

### ISSUE THREAD

**Issue by rtoma** [projectcalico/libnetwork-plugin#109]
Imagine a libnetwork plugin configured with a (new) config key like:

```
CALICO_WORKLOADENDPOINT_LABELS=foo=bar,baz=quux
```

Resulting in all workloadendpoints created by that plugin to have 2 labels set at create time:
- foo: bar
- baz: quux

This allows us to add labels describing the Mesos agent: datacenter, rack, core count etc.

Probably not useful for policies and Felix, but it allows 'ecosystem' tools to gather information currently not available.

I will submit a PR, but I wanted to open an issue for discussion first.

**Comment by tomdee** [comment]
I have no objection to this. I think it could be a useful feature and should be a very small amount of code.

**Comment by rtoma** [comment]
Our need for this is gone, so I am won't fix closing this.
