### ISSUE TITLE
Question: security code review

### ISSUE THREAD

**Issue by chiel1980** [projectcalico/libnetwork-plugin#110]
Hi,

Did you guys ever did a security review on your code by an external party?
And if yes, are you willing to share these results or can we find it back in some specifc commits?
We are scheduling a code review by an external security company and if you want, we would like to share these results with you/the community as feedback to improve the product :)

Michiel

**Comment by tomdee** [comment]
See answer to https://github.com/projectcalico/felix/issues/1225

**Comment by tomdee** [comment]
I'm going to close this as hopefully your question has been answered. I look forward to working with you more on this though!
