### ISSUE TITLE
libnetwork-plugin ippools affinity

### ISSUE THREAD

**Issue by markfra** [projectcalico/libnetwork-plugin#113]
We are looking for a way to define affinity between calico ippools and host(endpoints).

This request is a bit like: https://github.com/projectcalico/calico-cni/issues/152 but we are (obviously) using libnetwork-plugin.
Our use-case is that we have hard limits on ip-space that we can use per environment and want to be in control of who is using what. We also have 1 etcd cluster for all environments because we want to glue our "legacy" environments to these new environments, and apply policies through felix.

Because currently the ippools live in /calico/v1/ipam/v4/pool we cannot control the usage of them.

Is there currently any way to pin pools to certain hosts(endpoints)? If not we are happy to create this functionality, but then we need some guidelines.

**Comment by tomdee** [comment]
I think this is already supported. If you create your "networks" with a `--subnet` flag, that can point at a calico IPPool. Then containers created on that network will be allocated an address from that pool.

Code for it is here - https://github.com/projectcalico/libnetwork-plugin/blob/master/driver/ipam_driver.go#L135:L154

**Comment by markfra** [comment]
I have been able to confirm this, using: docker network create --driver=calico --ipam-driver=calico-ipam --subnet=x.x.x.x/xx  test-network.

Thanks!
