### ISSUE TITLE
Test with (and document) multiple versions of docker

### ISSUE THREAD

**Issue by tomdee** [projectcalico/libnetwork-plugin#137]
Testing is currently just using the latest Docker RC.

We should test a few previous releases and document what works and what doesn't.

**Comment by rtoma** [comment]
👍 
Quick fix would be to change rc-dind into a pinned version, so any issues are reproducible.

And maybe not use/test RC's? I saw weird temporary container IDs in NetworkInspect responses with 1.3.0-rc3, but gone in -rc5.

**Comment by tomdee** [comment]
Yep, I was using `rc-dind` to get some recent fixes, and I kind of expected 1.13 to have shipped already. 

The use of dind should make it easy to test with different docker versions (or even RCs) but we probably need a way of annotating tests as being specific to certain versions.
