### ISSUE TITLE
Reserving addresses using Calico IPAM is unwanted in current network driver

### ISSUE THREAD

**Issue by tomdee** [projectcalico/libnetwork-plugin#15]
We reserve the addresses but shouldn't need to. It slows things down and increases etcd occupancy.

Instead, let's just have the restriction that pools can't be shared between orchestrators that use Calico IPAM and those that don't.

Don't forget to update readme

**Comment by robbrockbank** [comment]
Looks like we already don't allocate IPs in the pool.  Closing.
