### ISSUE TITLE
libnetwork doesn't work on docker 1.10 and below

### ISSUE THREAD

**Issue by liaoyupeng** [projectcalico/libnetwork-plugin#151]
the removal of 

https://github.com/projectcalico/libnetwork-plugin/commit/d09af93bdb3b8454a8e83738ae6fd8fc92e32e19#diff-ed71230051def807b9b937271d6fb304L255

actually assumed that the docker-side fix is already in place, which requires docker 1.11+.

**Comment by tmjd** [comment]
@caseydavenport If we want to continue to support docker 1.10 we should undo that change.  If not then we should document it and possibly add in a check if possible.

**Comment by caseydavenport** [comment]
I don't think we plan on fixing this - users will need to update to 1.11+
