### ISSUE TITLE
master version isn't passing calico repo STs

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/libnetwork-plugin#155]
Working on getting calico STs running against my felix PR, I tried running calico repo STs against the "master" release stream, so it pulled in master of all components.  the ST run failed so I pared back all the versions to v2.3 and tried revving them to "master" one by one.

I found that the STs failed with libnetwork-plugin revved to master and all other projects pinned to v2.3 versions.

## Expected Behavior

Passing STs with libnetwork-plugin revved to master.

## Current Behavior

These tests fail:
```
[fail] 19.50% tests.st.bgp.test_node_status_resilience.TestNodeStatusResilience.test_node_status_resilience_1: 102.3461s
[fail] 15.83% tests.st.bgp.test_node_status_resilience.TestNodeStatusResilience.test_node_status_resilience_0: 83.0748s
```

The full log is available here: https://semaphoreci.com/calico/calico/branches/pull-request-895/builds/9 (which was a test of this commit: https://github.com/projectcalico/calico/commit/8642112752d874869ba113e719406d57c2913071)

## Possible Solution

Looks like we've had a gap in our CI so we didn't catch this in a timely fashion. 

## Steps to Reproduce (for bugs)

1. Check out calico repo
2. Copy the v2.3 versions down to the master section
3. Modify the libnetwork-plugin version to be master
4. Run `sudo make clean; sudo make RELEASE_STREAM=master calico/node st`

## Your Environment

* Docker version: 17.03
* Libnetwork-plugin version: master 
* How you deployed the libnetwork plugin:
* Operating System and version: Semaphore CI Ubuntu 16.04
* Link to your project (optional):

**Comment by robbrockbank** [comment]
@fasaxc I've run this locally several times with master and it's passing for me.

Also, the particular test failures are related to BGP restarts so I'm struggling to see a correlation with the libnetwork plugin.

**Comment by caseydavenport** [comment]
I don't think this belongs in v2.4, since we're not planning on releasing a new libnetwork-plugin for 2.4.

LMK if you think otherwise and we can discuss.

**Comment by tomdee** [comment]
@fasaxc the log is no longer available

**Comment by fasaxc** [comment]
I put up a PR that repros the issue on Semaphore (which now runs the master RELEASE_STREAM by default): https://github.com/projectcalico/calico/pull/949

**Comment by fasaxc** [comment]
Full failing log, copied to a gist: https://gist.github.com/fasaxc/23a2aacafea2faf0755a0ef3fe97129e

**Comment by tomdee** [comment]
So, one of the 22 or so commits to master since the last release of libnetwork-plugin is causing problems for the two BGP tests above. One of these commits  - https://github.com/projectcalico/libnetwork-plugin/compare/v1.1.0...master
