### ISSUE TITLE
Port mapping doesn't work

### ISSUE THREAD

**Issue by scltee** [projectcalico/libnetwork-plugin#18]
When creating a container, the `-p` option to publish a port on the container to the host doesn't work on a Calico network.

If created with Docker default networking, then the port mapping survives when the container is added to a Calico network, but as soon as the container is removed from the Docker network, the port mapping disappears.

**Comment by tomdee** [comment]
I just tested this with RC-3 and it works for me.

Could you be hitting this https://github.com/docker/libnetwork/issues/716

If you're still having problems, could you detail the steps I would need to take to repro the problem?

**Comment by scltee** [comment]
Interesting, it's now working for me as well. I wasn't hitting that other issue, the port mapping really wasn't working before, but I started using a different system at some point yesterday and the issue seems to have disappeared. I'll just have to put it down to something wrong with the system I was using.

**Comment by robbrockbank** [comment]
@scltee - I'll close this for now, but feel free to re-open if you start hitting this again.
