### ISSUE TITLE
lvs (linux virtual server) in libnetwork

### ISSUE THREAD

**Issue by allanhung** [projectcalico/libnetwork-plugin#33]
Hi, I had test lvs (linux virtual server) for docker. When I use libnetwork driver, it can't work correctly.
I had created a demo project to re-procedure it. (https://github.com/allanhung/docker-load-balancer)
Please read the demo.txt for create the demo env and run the './run.sh VIP'.
When I execute 'curl VIP', it will be responsed for the docker with bridge driver.  And it will not response for the libnetwork driver.  I have no idea what's wrong.  Please help.  Thanks a lot.

**Comment by robbrockbank** [comment]
Hi Allan,  I'll run through your instructions and see how I get on.  Rob

**Comment by robbrockbank** [comment]
Hi @allanhung 

I've not had any luck getting your script to work on my machine.  I wanted to first get this working with the docker bridge driver to make sure I was on the same page as you, but I couldn't get this working with the docker bridge driver either.

To try out the docker bridge driver, I created the networking as follows:
NETID=$(sudo docker network create lvsnet)

With this change it should be using the default bridge driver for the network, but I was unable to get the curl command to respond.  Perhaps you could tell me a little more about how you expect this to work and I'll do some digging.

**Comment by allanhung** [comment]
Hi @robbrockbank 
In origin demo, I put two real server in lvs, one use bridge driver and the other use calico driver.
When you curl the vip, it will forward the request round robin to the real server.
If there is no reponse, the request is forward to the docker with calico driver.
So just curl the vip again, if the request forward to docker with bridge driver, it should be responsed like : <html>
    <head>
        <title>Host: 0e6f3378a0d6</title>
    </head>
    <body>
        <p>This host id is: 0e6f3378a0d6 
    </body>
</html>
I think put demo with bridge and calico  make the demo complex. 
I had created the demo sperate bridge and calico.
You can test with run_with_bridge.sh and the curl the vip.
It will respose correctly.
And test with run_with_calico.sh, it will no response.
Appreciate your help.

**Comment by allanhung** [comment]
Sorry for press wrong button with close.

**Comment by allanhung** [comment]
Hi @robbrockbank

There is no need to change NETID to $(sudo docker network create lvsnet).  If you want to use bridge driver, I think just use docker run without net flag.  The bridge driver is default option.

Let me describe my issue clearly. The lvs has two roles. One is director and the other is realserver.  Director will get client request then forward to realserver.  If I use libnetwork driver for realserver, the lvs will failed. If I use bridge driver for realserver, everything is ok.

I renew the readme in my demo. (https://github.com/allanhung/docker-load-balancer)
And attach the image of about the demo script.

If it's ok, I think we can use teamview or someway you familiar with, I can demo the issue for you.

Really appreciate your help.

**Comment by allanhung** [comment]
Hi @robbrockbank
After some research, I found the same issue with this.
https://github.com/docker/libnetwork/pull/707
https://github.com/docker/libnetwork/issues/798
Thanks.

**Comment by allanhung** [comment]
Hi @robbrockbank,
In the lvs dr mode (http://www.linuxvirtualserver.org/VS-DRouting.html), the load balancer simply changes the mac address of the data frame to that of the chosen server and restransmits it on the lan.
The calico network uses L3, so after change to lvs tunnel mode (http://www.linuxvirtualserver.org/VS-IPTunneling.html). The issue is solved.
Cheers!!

**Comment by robbrockbank** [comment]
@allunhung

**Comment by robbrockbank** [comment]
@allanhung   Glad you managed to figure this out.  Apologies about the silence on our end - it's the usual holiday season here for us.

**Comment by allanhung** [comment]
@robbrockbank That's ok. Wish you have a nice holiday and happy new year.
