### ISSUE TITLE
Add ability to specify profiles as a docker network option

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/libnetwork-plugin#44]
`docker network create` allows you to specify arbitrary options that are passed through to the network driver.

I'd like to add an option to specify which calico profiles the network corresponds to.  Useful for a couple of reasons:
-  You get to name the profile associated with a network rather than the libnetwork plugin assigning an arbitrary (and long) UUID for the profile.
-  You could specify multiple profiles.  When creating an Endpoint, all of the profiles would be added in the order they are listed.

This would simplify finding the profile so that you can apply advanced policy to a libnetwork'ed container.  It would also allow you to easily specify multiple profiles per endpoint.  This does not workaround the problem of tweaking which profiles are on an endpoint once the endpoint is created -- however IMHO since a container is lightweight you should just restart the container pointing at a network with the correct profiles.

To implement:
-  Read in the `calico-profile=<list of profiles>` option and store in our private Network data.
-  When creating the Calico Endpoint data, set the profiles as per the data in the Network data.  By default, we should create any profiles that don't exist.
-  If the profiles list is not specified we revert to the current behavior
-  Maybe also add a `calico-profile-create=true|false (default true)` to specify whether we should attempt to create the profiles when they do not exist (or whether we should just assume that they exist). 

We should then update the calico-container docs to reference this new way to access advanced policy in the libnetwork case.

**Comment by TrimBiggs** [comment]
An enhancement was made to the `calicoctl` command line tool that works similarly to this proposed change, though this issue would provide additional features if implemented.

The `calicoctl` enhancement allows users to specify the name of a Docker network as the name of a profile when running `calicoctl profile` commands.

**Comment by tomdee** [comment]
THe plugin now creates profiles using hte network name so closing this issue.
