### ISSUE TITLE
Flaky test  - mainline multi-host

### ISSUE THREAD

**Issue by tomdee** [projectcalico/libnetwork-plugin#58]
The mainline test is failing intermittently (maybe one in ten runs). This is annoying and should be fixed
```
======================================================================
FAIL: Run a mainline multi-host test.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tests/st/libnetwork/test_mainline_multi_host.py", line 96, in test_multi_host
    workload_h2n1_1])
  File "/tests/st/utils/utils.py", line 122, in wrapped
    raise e
AssertionError: workload_h1n1_1 cannot ping 10.0.0.2
```

**Comment by djosborne** [comment]
Looks like I implemented half of this by [adding a retries passthrough](https://github.com/projectcalico/libcalico/pull/119) to test framework assertion function that is failing.

Still need to increase the retries in the caller.
