### ISSUE TITLE
Add (back) IPv6 support

### ISSUE THREAD

**Issue by tomdee** [projectcalico/libnetwork-plugin#72]
IPv6 support was potentially broken in previous Python versions and support was removed during the Go rewrite. We want to add it back.

I don't think we can until this Docker bug is fixed - https://github.com/docker/docker/issues/28055

When we do, we'll need to make the following changes:
RequestPool - Return the correct pool, poolID and gateway.
For reference the IPv4 reponse is`{"PoolID":"CalicoPoolIPv4","Pool":"0.0.0.0/0","Data":{"com.docker.network.gateway":"0.0.0.0/0"}}`
RequestAddress - Check whether the request.PoolID is the V6 poolID. If so then take V6 actions.
CreateNetwork - Check the IP6Data for non-Calico IPAM drivers
CreateEndpoint - Ensure that IP address in `AddressIPv6` makes it into the Calico endpoint object
Join - Fetch the IPv6 link local address from the host veth and add that as a route into the reponse.

**Comment by djosborne** [comment]
Once this issue is resolved please assign the next release milestone to https://github.com/projectcalico/calico/issues/227
