### ISSUE TITLE
Problem upgrading from Python version to Go version

### ISSUE THREAD

**Issue by frostynova** [projectcalico/libnetwork-plugin#89]
We have libnetwork plugin running in the production environment, so i wonder if the go version release, can we migrate online?

**Comment by tomdee** [comment]
You should be able to but remember that IPV6 isn't supported, the ipam driver is renamed to `calico-ipam` and `calico-ipam` must be used. We haven't tested it extensively, so please test it locally before running the  migration on your production environment! Of course, we're keen to hear any feedback.

**Comment by frostynova** [comment]
@tomdee We have tried the new version, but got an error when starting container:

```
Error response from daemon: Plugin does not implement the requested driver
```

I think this is because the rename of `ipam` driver. But what should we do to join the old network after upgrading the calico node?

**Comment by tomdee** [comment]
The rename of the ipam driver is caused by this upstream issue - https://github.com/docker/go-plugins-helpers/issues/36

As far as I can tell, Docker doesn't allow the IPAM driver being used for a docker network to be updated after it's been created. https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/create-a-network

**Comment by CMGS** [comment]
I modified docker network data in etcd (docker/network/v1.0/network), changed ipamType from calico to calico-ipam and it seems work well for me.

however, the fresh container started with previous network and new calico can not connected by exists containers. I checked the route table and it was correct, so how to fix it.

**Comment by frostynova** [comment]
@tomdee We found another issue:

Python version plugin using `network id` to auto create profile
But Go version using `network name` which will prevent the upgrade node join the old SDN network.

**Comment by frostynova** [comment]
@tomdee I tried to edit etcd key:

`calico/v1/host/${host}/workload/libnetwork/libnetwork/endpoint/${endpoint}`

changed the new version node's profile from `name` to `id`, then ping is ok.

So is that safe for us to modify the etcd like above?

**Comment by tomdee** [comment]
It would be great if we could come up with a decent process to upgrading from the Python version to the Go version. e.g. a script or a documented procedure. Until that happens, the upgrade is unsupported.
