### ISSUE TITLE
libnetwork-plugin should support a configurable location for the Docker API

### ISSUE THREAD

**Issue by tomdee** [projectcalico/libnetwork-plugin#90]
At the moment it only works with the default docker.sock location

**Comment by tomdee** [comment]
Actually, we use an `EnvClient` so we support all the standard env vars - e.g. `DOCKER_HOST` so maybe this just needs a docs change

**Comment by caseydavenport** [comment]
@gunjan5 looks like this just needs retest / documentation work.

**Comment by gunjan5** [comment]
so this doesn't seem to work at 2 places at least:
1. `calicoctl node run` command always mounts the default `/var/run/docker.sock` right now
2. When I manually configure and start `dockerd` to listen to a tcp port `dockerd -D -H tcp://172.17.8.101:2376 &` and set the env var `DOCKER_HOST=tcp://172.17.8.101:2376` when starting calico-node, it starts fine:
```bash
$ docker run --net=host --privileged --name=calico-node -d --restart=always -e NO_DEFAULT_POOLS= -e CALICO_LIBNETWORK_ENABLED=true -e ETCD_ENDPOINTS=http://172.17.8.101:2379 -e ETCD_AUTHORITY= -e ETCD_SCHEME= -e NODENAME=calico-01 -e CALICO_NETWORKING_BACKEND=bird -e DOCKER_HOST=tcp://172.17.8.101:2376 -v /run/docker/plugins:/run/docker/plugins -v /var/run/docker.sock:/var/run/docker.sock -v /var/run/calico:/var/run/calico -v /lib/modules:/lib/modules -v /var/log/calico:/var/log/calico -v /run/docker/plugins:/run/docker/plugins calico/node:latest

$ docker ps
DEBU[2333] Calling GET /v1.24/containers/json
CONTAINER ID        IMAGE                COMMAND             CREATED             STATUS              PORTS               NAMES
8a9152c19ceb        calico/node:latest   "start_runit"       3 minutes ago       Up 3 minutes                            calico-node
```

BUT, when I try to add a docker network, I get this:
```bash 
$ docker network create --driver=calico --ipam-driver=calico-ipam myCaliNet2
DEBU[2134] Calling POST /v1.24/networks/create
DEBU[2134] form data: {"CheckDuplicate":true,"Driver":"calico","EnableIPv6":false,"IPAM":{"Config":[],"Driver":"calico-ipam","Options":{}},"Internal":false,"Labels":{},"Name":"myCaliNet2","Options":{}}
DEBU[2134] Allocating IPv4 pools for network myCaliNet2 (7ef44b18007ad0565f6178a9e2f51e4b60c72feca6500088168e4836193e1d30)
DEBU[2134] releasing IPv4 pools from network myCaliNet2 (7ef44b18007ad0565f6178a9e2f51e4b60c72feca6500088168e4836193e1d30)
ERRO[2134] Handler for POST /v1.24/networks/create returned error: datastore for scope "global" is not initialized
Error response from daemon: datastore for scope "global" is not initialized
```

Not sure we want to add any docs for this in this state, unless I'm doing something wrong? @tomdee

**Comment by tomdee** [comment]
@gunjan5 That second error is probably because you didn't set a data store for your dockerd

**Comment by tomdee** [comment]
--cluster-store=etcd://a.b.c.d:2379

**Comment by caseydavenport** [comment]
We need to mark this as a release blocker or kick it out of the v1.0.0 release.  @tomdee @gunjan5 

> calicoctl node run command always mounts the default /var/run/docker.sock right now

This is just a calicoctl issue, not a calico/node or libnetwork issue so shouldn't block this as far as I can tell.

**Comment by gunjan5** [comment]
@caseydavenport I will create another issue in calico-containers for the calicoctl issue, it shouldn't block this, and I'm retesting the other one and if that works we can close this

**Comment by gunjan5** [comment]
ok so after passing --cluster-store=etcd://a.b.c.d:2379 it seems to work, I'm able to create networks and able to ping across the hosts. I have created an issue for `calicoctl node run` mounting `/var/run/docker.sock` https://github.com/projectcalico/calico-containers/issues/1388 
Closing this issue since libnetwork-plugin works as expected

**Comment by tomdee** [comment]
Reopening as I don't think you've solved this.

As as user, if I'm using the libnetwork-plugin through calico/node started with calicoctl, I can't choose the DOCKER_HOST still, or am I missing something?

I see you've raised projectcalico/calico-containers#1388 but that doesn't solve my concern above.

**Comment by gunjan5** [comment]
@tomdee I've created an issue in calico-containers for this (linked #1404). Since it doesn't require a change in libnetwork-plugin I will close this issue and carry on in calico-containers
